### ISSUE TITLE
Windows 10 Drivers please :)

### ISSUE THREAD

**Issue by hxhieu** [LattePandaTeam/LattePanda-Win10-Software#1]
Hi there,

Just got my LP and awesome guys!
Did a clean install from official MS Win10 ISO and got the drivers from this thread: http://www.lattepanda.com/forum/viewtopic.php?f=5&t=79&sid=1ae6c8ccc4d8062651df777bd5d07c46

But could we have the drivers here for feedback and support?

Cheers,
H

**Comment by LattePanda** [comment]
Hi hxhieu,
Thanks for your comments. Yes, we've packaged the official drivers for LattePanda. Just really need some user feedback for if it works fine.

Please download the drivers here:
https://drive.google.com/open?id=0Bzm23BxAV00pRUgtb0ZqUHJYT3c

Look forward to your feedback.:)

Best

**Comment by hxhieu** [comment]
The Broadcom wifi driver didn't work with the package I got from the forums link mentioned in my previous post.
I will try this one out later today and will let you know :)

**Comment by hxhieu** [comment]
Hi,
The Broadcom driver is now working well yay! But what is the reason of having all the 64bit drivers INF files suffixed with .MP3. I had to rename them to get the script to run.

Cheers,
H

**Comment by LattePanda** [comment]
Cool. Thanks for your fast feedback. However I can't find .mp3 files in my folder. Is it possible to be a protection from your antivirus software? Great to hear that the driver works for you anyway. 

Will share with other users for more testing before uploading to the github.

**Comment by hxhieu** [comment]
I was talking about the 4GB/64GB/64bit dirver and here is an example you can see .inf.mp3
Pretty much all .inf files in this package have this issue.

https://drive.google.com/folderview?id=0Bzm23BxAV00pY3MtODQydVJnejQ&usp=drive_web&tid=0Bzm23BxAV00pRUgtb0ZqUHJYT3c

Cheers,
H

**Comment by BOYNOYNUDEE** [comment]
I already download driver. However, anybody can tell me how can I install driver :(:(. Please.

**Comment by LattePanda** [comment]
The link may be helpful: https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/Drivers/LattePanda_2G32GB_Drivers/CHT%20T3%20MRD%20PR2%20Driver%20WW51.2/MRD_Drivers%20install%20Readme.txt

[https://avatars3.githubusercontent.com/u/17541360?v=3&s=400]<https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/Drivers/LattePanda_2G32GB_Drivers/CHT%20T3%20MRD%20PR2%20Driver%20WW51.2/MRD_Drivers%20install%20Readme.txt>

LattePandaTeam/LattePanda-Win10-Software<https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/Drivers/LattePanda_2G32GB_Drivers/CHT%20T3%20MRD%20PR2%20Driver%20WW51.2/MRD_Drivers%20install%20Readme.txt>
github.com
Contribute to LattePanda-Win10-Software development by creating an account on GitHub.





Best Regards,
Kelvin Sun
________________________________

**Comment by BOYNOYNUDEE** [comment]
Thanks for your kindness response.
First of all, my LP is 4G64GB  platform.  I'd done download 4G64GB driver and update WIFI.  There is still the same error shown "code 10".  Even thought, I download 2G32GB driver for wifi as your recommend.  It showed that I cannot install it because it's not proper platform.

What should  I do?

By the way, Wifi is work since I run it at the first time.  Wifi doesn't work again after I'd clean install Windows 10 Pro.   I'd already to change suffix filename as @ hxhieu 's comment; however, it doesn't work at all.

Appreciated all comment to help me out please. :(:(:(

**Comment by Philanilenin** [comment]
hi 
i recently purchased 10 latte panda units & updated the bios for auto start up & now two of my units are no longer starting up,how do i resolve this issue.By the way how do i do a clean installation of windows on them?

**Comment by paullee1978** [comment]
![lattepanda-win10-driver-virus](https://cloud.githubusercontent.com/assets/28797946/26231949/1f0eac94-3c85-11e7-97aa-fcec7a8f7425.png)

I found out there is Trojan virus in your lattepanda win10 driver
