### ISSUE TITLE
LP Windows activation issue

### ISSUE THREAD

**Issue by rd-tecnoroll** [LattePandaTeam/LattePanda-Win10-Software#10]
Dear guys, great works !
I have just bought the LP board from RS-Components and everything seems to work properly with the only exception of the windows license.
The board came with a yellow lable on the USB connetors claiming "ACTIVATED" version of the installed windows.
Unfortunately after powering up and booting the board I have got a message from the OS telling me that the installed windows product key is not valid. 
It seems that during production a key was installed but not for the right OS. 
The LP board is the 2/32Gb version and it came with pre-loaded Windows10 Home edition as it should.
Do you have any suggestion or could you provide me a valid key to install on the LP board ?

Thanks & regards

Lorenzo

**Comment by LattePanda** [comment]
Dear friend,

Sorry for the inconvenience and thanks for your great support.
This should be a latest production issue when burning the key to the products. We recognize this problem when some users reported to us. 
So we did a simple guide for you to activate your device properly. It will fix that. 

Check the link below:
http://www.lattepanda.com/forum/viewtopic.php?f=10&t=1271&p=5529#p5529

Feel free to contact with us if any problem! ;)

Best,
Lauren
