### ISSUE TITLE
LP BIOS install problem

### ISSUE THREAD

**Issue by oguzhankarabulut** [LattePandaTeam/LattePanda-Win10-Software#11]
When i was trying to install linux to LP, i deleted the window10 with gparted. I followed some tutorials about install linux but i was unsuccesful. Now i downloaded BIOS-beta and done everything like you wrote. I formatted my disk FAT32 and i copied bios file to usb disk and i plug gedthe disk LP and plugged the microusb cable. But nothing was done. Monitor doesnt working, BIOS returning "fs1" screen did not come, LP did not give a power to keyboard and mouse. Please help me

**Comment by Lauren-ED209** [comment]
Hi, did you try to set the boot option from bios? If not, check this to figure out the steps for setting. http://lattepanda.com/forum/viewtopic.php?f=10&t=1371&p=5994&hilit=usb+boot#p5994

And here's a detail dual boot tutorial to run Windows and Linux both on LattePanda:
http://lattepanda.com/forum/viewtopic.php?f=6&t=1168&p=4988&hilit=dual+boot+linux#p4988

Hope it's helpful!

Best

**Comment by oguzhankarabulut** [comment]
Keyboard and monitor is not working. How can i open BIOS Screen ?

**Comment by Lauren-ED209** [comment]
When did you find that usb devices won't work? Let me check with our software guy to find cure...

**Comment by Lauren-ED209** [comment]
Did you try the USB 3.0 port?

**Comment by Lauren-ED209** [comment]
if the usb port doesn't work, it could be a bios issue. You may need to refresh the bios using bios programmer first. Then reinstall the system. 
Check out this: http://www.lattepanda.com/forum/viewtopic.php?f=6&t=386&hilit=bios+programmer
