### ISSUE TITLE
Boot on Power

### ISSUE THREAD

**Issue by catvvvveasel** [LattePandaTeam/LattePanda-Win10-Software#13]
Bios/LattePanda v1.0 for Z8300 only/Auto Power on BIOS/4G/LattePanda 4G+64GB.zip

I've updated the bios, I think, it did all the checking and writing, but I still can't find a boot on power on option in the bios, and it doesn't do it by default. How do I enable it, which section should it be?

**Comment by magdesign** [comment]
There is no option in BIOS, when flashing to the Power-On bios it will automatically power on when connected to the 12V power plug (seems not to work with usb-c).

**Comment by KennethLavrsen** [comment]
Does not work with USB-C??
What the f***?
Will they ever fix this shit
