### ISSUE TITLE
Locked out of LattePanda after setting BIOS password

### ISSUE THREAD

**Issue by rk3990** [LattePandaTeam/LattePanda-Win10-Software#19]
Hello, I recently bought a LP (CPU: Intel Atom Z8350/RAM: 4GB/ eMMC: 64GB) about a week ago and accessed the BIOS to find a way to protect it with a BIOS password and after setting a password and rebooting it, I was unable to type my password in using a USB keyboard via any USB slots on the board. My keyboard(s) both wired and wireless are unrecognised by the LP's USB slots at this point, and I have even tried to re-flash it via USB, but the LP asks again for the password, thus reinstalling the BIOS though USB isn't possible.

I have tried everything in the forums, to recover the BIOS and chose the hardware flasher route using a CH341A SPI Flasher, with a SOIC test clip with no success. I'm not sure what can be done to resolve this issue at this point other than sending the board for a RMA. If not, what else can be done to resolve this issue?

**Comment by CocoXiakou** [comment]
The bios password function looks well to me.
I think you can try to re-write the BIOS again. If it can not be fixed, you can contact  LattePanda Team for repair I guess.

**Comment by rk3990** [comment]
@LattePanda @CocoXiakou I've already tried reflashing the BIOS a couple of times using the SPI flashers and my LattePanda was still unable to boot up. In the end, I just sent it back and got a refund for it instead. Thank you for your help.
