### ISSUE TITLE
PXE support?

### ISSUE THREAD

**Issue by doomedraven** [LattePandaTeam/LattePanda-Win10-Software#2]
Hello, thanks you for great device :)
I can't find/enable PXE boot, do you have planned do add it?

best regards

**Comment by doomedraven** [comment]
@LattePanda any possibility?

**Comment by Chris6S** [comment]
I'd like to know this too

**Comment by LattePanda** [comment]
Really sorry for the silence. We don't support PXE boot officially yet. Would you please kindly share your opinion about the value of PXE boot? 

Hope you can find this reply if you still want to talk about this question. 
Thanks for your great support for LattePanda!

Best

**Comment by doomedraven** [comment]
@LattePanda ok let me reexplain what i posted in official forum :)

here going few of the important points of PXE value: and i know a lot of people who bought it expecting have PXE, but all of us we failed what we was need to ask before buy, so here goes my friends and mine view of it:

1. `sysadmins` -> can create the desktop for end users which will download image of workstation and boot always with clean image for host with all required software
2. `researchers/malware analysis` -> bare metal analysis, as latte panda has good hardware, it would be awesome integration with for example cuckoo sandbox, so no vm detection could be possible

im sure people have more points why they need it, but i think this 2 is pretty solid :) let me know if you think finally add it, as basically im looking to sell it with, if there no PXE support

**Comment by LattePanda** [comment]
Dear Doomedraven,

Great. I read your forum conversation. 

Appreciate your fast response. I see. Let me check with our bios developers to confirm if the hardware design can support this feature! 
According to your introduction, I think it's definitely worth to make it. The only thing I need to check if the possibility and cost of development. Will update my understanding after internal discussion!

And how did you use LattePanda right now? Are you a teacher or IT manager? ;)

Best
Lauren

**Comment by doomedraven** [comment]
great let us know about final decision, if that would be possible that would be really awesome feature, as with this hardware and pxe support it could boost lattepanda sales(in my opinion as i not saw something similar with this price) 

at the moment I'm not used it at all, bcz i have my server for what I need, and for windows base stuff it not does what I expected(PXE related stuff), lets say, kinda sysadmin ;)

hope to read you soon, and happy to at least get some kind of response :)

best regards
Andriy

**Comment by LattePanda** [comment]
Dear Doomedraven,

Would you mind to introduce more about what kind of products you are using now? And what's similar products in the market right now? That will be great helpful for me to have a further understanding about the market size you talking about. Then I can talk with our leader to make the decision. :)

Appreciate your great feedback. I'm pushing this process. 

Best

**Comment by doomedraven** [comment]
hello.

well all that devices is for fun nothing for production, as their capability is not so advanced(for what i want/need), minix x7 with [ultimate server](https://play.google.com/store/apps/details?id=com.icecoldapps.serversultimate&hl=en) and raspberry 3 was as docker host. played with another small devices, but meh, all that is now replaced with one real server. im more interested in device which i could use for end user and each day load clean image with all required software, like normal desktop, my lattepanda is 4gb ram and 64mmc, so that is more than enough for normal end users :)

best regards

**Comment by LattePanda** [comment]
@doomedraven check out this!!!
A video tutorial for enabling PXE boot on LattePanda! 
https://www.youtube.com/watch?v=rHSE60w1lh8

**Comment by doomedraven** [comment]
oh guys that is pure love <3, thanks a lot, going to test it in few hours, and will close this.

Thanks a lot :)

**Comment by doomedraven** [comment]
just tested, works, may require small fix to startup file, if fs is different, but it works just fine :)
uniq thing, for some reason bios doesn't save my settings, so i need manually change to uefi shell all the time to be able to load by pxe, any idea why it can happens?

**Comment by doomedraven** [comment]
@LattePanda in bios `save and exit` and `save and reset` is the same, if you click save and exit it ask save and reset yes/no

**Comment by doomedraven** [comment]
@LattePanda even if im in `save & exit` and selecting save changes, later when i want to enter efi shell it pops `save configuration and reset`, can you check and fix this bug? it reset full conf in bios, and i can't disable some security features which doesn't allow me finish the PXE boot and grabbing device image

**Comment by doomedraven** [comment]
basically i need to be able disable TCG in advanced `security device support` http://www.thinkwiki.org/wiki/Embedded_Security_Subsystem

**Comment by TomReddish-MVC** [comment]
Is there any update on PXE booting built into the BIOS?

**Comment by doomedraven** [comment]
no, the bios doesn't save settigns so you need to set pxe by yourself on each boot, totally useless

**Comment by TomReddish-MVC** [comment]
They aren't planning on fixing that issue either? 

The fix they posted also requires you to put your hands on every board you want to PXE. We want to PXE boot groups (10-20 at a time) and re-image them. 

Looks like this board is not going to work for us unfortunately.

**Comment by doomedraven** [comment]
i wouldn't expect support from them at all, they responded after year with work done by 3rd part(looks like) and nothing else, 

yep i was need to ask also if pxe is supported before buying this board, totally not recommended if you want PXE related thing, at least they could say no sorry we don't support and and don't plan to support but you see not looks like they care to much(was asked by many persons in forum)
