### ISSUE TITLE
No source for drivers or BIOS.

### ISSUE THREAD

**Issue by R030t1** [LattePandaTeam/LattePanda-Win10-Software#21]
Please provide source for both, thank you!

**Comment by LattePanda** [comment]
Dear friend,
Because we have agreement with BIOS source provider, so we don't have right to open source the BIOS code.. Hope you can understand...

**Comment by R030t1** [comment]
Can the BIOS be replaced, or is the BIOS signed and the signature enforced by the boot ROM on the board?

I originally considered the availability of source code when picking the product. I guess I should have looked a lot more closely, I figured being on GitHub would be enough.
