### ISSUE TITLE
S70CR200-CC55G Firmware Missing From Repo

### ISSUE THREAD

**Issue by raidensnake** [LattePandaTeam/LattePanda-Win10-Software#24]
@lattepanda Can you upload a copy of the S70CR200-CC55G firmware? My lattepanda crashed all of a sudden for some unknown reason decided to brick itself with the solid red light. I have the SPI programming tool as mentioned in the guide but I need the firmware file for it.

**Comment by LattePanda** [comment]
@raidensnake ,thanks for your great support for us.
Please check the message replied from forum.
https://www.lattepanda.com/topic-f10t17119p25536.html#p25536

**Comment by LattePanda** [comment]
And let us follow via forum also. Thanks!
