### ISSUE TITLE
Audio driver

### ISSUE THREAD

**Issue by loadko** [LattePandaTeam/LattePanda-Win10-Software#25]
I can´t install audio drivers on Windows 10 Enterprise LTSC 2019 64bit on LattePanda 32GB/2GB.
When I try to install these drivers manually, I get "Driver is not intended for this platform".

Any solution?

**Comment by LattePanda** [comment]
We are working on a new driver pack. We will try to release that after all testing. Thanks for your support.

**Comment by raidensnake** [comment]
you need to use the 4G 64-bit drivers. They do work on the 2G model as well.

**Comment by KingDinesh** [comment]
No, do not use 4G/64GB driver. It wont work, tried that and it makes the device unrecognizable.
I used this one.

https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=h62jg

Step 1. Run setup.exe
Step 2. Choose Extract, to a new folder (example: C:\Temp)
Step 3. Use Device Manager (Run->devmgmt.msc) to update or install device. Automatically or Manual doesn't matter 
Step 4. Delete unpacked files and folder

**Comment by enderaltin** [comment]
> LattePanda 32GB / 2GB üzerinde Windows 10 Enterprise LTSC 2019 64bit'e ses sürücüleri yükleyemiyorum.
> Bu sürücüleri el ile yüklemeye çalıştığımda, "Sürücü bu platform için tasarlanmamış" ı alıyorum.
> 

How to install CR110 Z8350 2gb / 32 64bit Win10?
