### ISSUE TITLE
Problem changing bios CR200 Z8350. Unable 64bit to 32bit

### ISSUE THREAD

**Issue by Molkor** [LattePandaTeam/LattePanda-Win10-Software#27]
Good afternoon:

We are unable to change the bios to 32 bits anymore with the [resource of this github.](https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/Bios/LattePanda%20V1.2%20for%20CR200%20Z8350%20only/2G%20version%2032bit%20BIOS/DF-BI-7-S70CR200-CC34E-004-A(64bit%20to%2032bit).zip) 

Entering in the Bios, the only data we see that changed its the _Build Date and Time_ 07/10/2018 11:19:37.

The message error appears when AMI Firmware Update utility is running.

- Check RomLayout..... Changed.
4c- Error: Rom file ROM layout is changed.

![IMG_20190515_182846](https://user-images.githubusercontent.com/50672898/57792534-8173b680-773f-11e9-9b00-b2b06cf2c0d0.jpg)

We change a lot of S70CR200 z8350 LP bios from 64 to 32 bits before, this is the first time we encounter thir problem.
Anyone has a solution for this situation?

**Comment by Molkor** [comment]
More data about the error 0x4c, from AMI Firmware Documentation:

The Error Message Information of ROM
AFU has added the check mechanism of ROM information. AFU would compare the information between updated ROM and on board ROM. If these ROMs have different information, AFU will show the error of 0x4C.
AMI extremely suggest users to stop choosing “Continue to update” if users do not comprehend ROM structure very much. The system will be crashed after BIOS update because of ROM information difference.

**Comment by raidensnake** [comment]
> Good afternoon:
> We are unable to change the bios to 32 bits anymore with the resource of this github.
> Entering in the Bios, the only data we see that changed its the Build Date and Time 07/10/2018 11:19:37.
> The message error appears when AMI Firmware Update utility is running.
> 
> Check RomLayout..... Changed.
> 4c- Error: Rom file ROM layout is changed.
> 
> 
> We change a lot of S70CR200 z8350 LP bios from 64 to 32 bits before, this is the first time we encounter thir problem.
> Anyone has a solution for this situation?

Unless you have the CH341A chip programmer with the clamp connector and step down voltage converter that's mentioned in this guide https://www.lattepanda.com/topic-f6t386.html?hilit=tutorial

There's no real other way to flash it.
