### ISSUE TITLE
Screen Orientation on 10" Screen

### ISSUE THREAD

**Issue by Athesis** [LattePandaTeam/LattePanda-Win10-Software#29]
The currently provided BIOS for 10.1" Displays only works in Portrait mode, is there a way to fix this? It's messing up USB-Touchscreens in it's orientation ... !

**Comment by LattePanda** [comment]
The LattePanda 10.1" display is portrait screen, it’s like an attribute and cannot be changed. Microsoft add the rotation function in the system, and you can use that to adapt the application. About the touch screen can you find a  jump cap or solder joint can adjust the XY axis manually? Some of them even have the built-in calibration feature to compatible with different brand 10.1” screen
