### ISSUE TITLE
BIOS Update failed

### ISSUE THREAD

**Issue by Kriechi** [LattePandaTeam/LattePanda-Win10-Software#3]
I tried to update my BIOS to the auto-boot version.
After putting preparing my thumb drive with the correct files,
I can see the LattePanda booting into the EFI console and running `startup.nsh`.
However, the last lines is an error message:

```
startup.nsh> afuefix64 DF-BI-7-S70CR110-C45B-001-C /b /p /n /x
30 - Error: Problem opening file for reading.
fs1:\>
```

I verified all files, and they match the one from this repository and are the correct version for my LattePanda (4/64GB).
How can I update my BIOS now?

**Comment by shimkh02** [comment]
Did you checked U-disk FAT32 form?

**Comment by LattePanda** [comment]
Dear friend,

All bios installation tutorial and materials are updated. Please try it again according to the latest updates. 
And feel free to post your problem on lattepanda.com/forum! 
User community and our support team will have a positive conversation with you together. 
Sorry for the delay. 

Thanks for your great support!

Best
