### ISSUE TITLE
(Re-) Flashing BIOS from LattePanda Delta doesn't work! The >README.md< is wrong. @LattePandaTeam

### ISSUE THREAD

**Issue by kiwibytes** [LattePandaTeam/LattePanda-Win10-Software#31]
I just tried to (re-) flash the BIOS from my @LattePanda Delta ... 

I did it, like it is described in your >README.md< ... [https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/BIOS%20for%20LattePanda%20Alpha%26Delta/README.md] ... but the "Firmware Update Utility" doesn't handle the "command" or "option" >/b< which is mentioned and therefore it doesn't worked! 

![shell_1](https://user-images.githubusercontent.com/56999126/67566372-e0464e80-f727-11e9-91cd-5c2d2305382f.jpg)

![shell_2](https://user-images.githubusercontent.com/56999126/67566383-ed633d80-f727-11e9-8a1f-13e102db0399.jpg)

![shell_3](https://user-images.githubusercontent.com/56999126/67566396-f48a4b80-f727-11e9-9751-601033124d55.jpg)

![shell_4](https://user-images.githubusercontent.com/56999126/67566404-f9e79600-f727-11e9-84da-688a66180e43.jpg)

I hope that someone with real knowledge can help me out!

**Comment by LattePanda** [comment]
Hi kiwibytes，thanks for your question.
Please delete the command "/b /p /n " .
![Delta BIOS reflash](https://user-images.githubusercontent.com/16882579/72677776-1f8ffb80-3adb-11ea-95c6-63ecb70a0a8a.jpg)
