### ISSUE TITLE
Bios Microcode Update

### ISSUE THREAD

**Issue by ricktendo** [LattePandaTeam/LattePanda-Win10-Software#34]
Would it be possible for you to update the Microcode file in the bios, current microcode is cpu706A1_plat01_ver00000022_2017-12-26_PRD_CA264967 before Specter and Meltdown vulnerabilities were patches.

Here you will find the latest Microcode: [cpu706A1_plat01_ver00000032_2019-08-28_PRD_21637812](https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu706A1_plat01_ver00000032_2019-08-28_PRD_21637812.bin)

**Comment by ricktendo** [comment]
Also here is the latest microcode for 706A8

https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu706A8_plat01_ver00000016_2019-08-29_PRD_17531470.bin

**Comment by LattePanda** [comment]
Thank you, Ricardo
I will let our engineer compare this microcode with our board.



Best Regards,

Cain Zhang

LattePanda Team

________________________________

**Comment by ricktendo** [comment]
Also can you update Intel CSTXE 4 Firmware to [v4.0.26.1334](https://mega.nz/file/eAM0gKrS#CuFpTQ6YuZzn9CIhH5Rdw_A-dqpLmD1b_R4MxcQww1Y)

[Intel Trusted Execution Engine:
Drivers, Firmware & System Tools](https://www.win-raid.com/t624f39-Intel-Trusted-Execution-Engine-Drivers-Firmware-amp-System-Tools.html)

**Comment by LattePanda** [comment]
Hi there
So far as I know, not all Microcode fit the CPU and normally, we will follow the guidance from Intel and use the most stable version with whole board.

And may I ask why you need update the code? and function you need to use has problem or bug?



Best Regards,

Cain Zhang

LattePanda Team

________________________________

**Comment by ricktendo** [comment]
The reason for my request is because of security fixes, these microcodes and TXE updates contain critical updates

**Comment by ricktendo** [comment]
Update: pleaes note the microcodes have been updated to 2020-06-09

https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu706A1_plat01_ver00000034_2020-06-09_PRD_FE4655B4.bin
https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu706A8_plat01_ver00000018_2020-06-09_PRD_1D9A5DFE.bin
