### ISSUE TITLE
Board can't detect large monitor 32:9 on boot

### ISSUE THREAD

**Issue by HungryNomad** [LattePandaTeam/LattePanda-Win10-Software#35]
I have a Samsung 49" CRG9 Dual QHD 5120 x 1440 (LC49RG90SSNXZA) 
On a fresh boot, the Latte Panda 800s will not connect to this monitor. Other systems work with the monitor and the Panda works on other monitors.

The workaround is to connect the Panda to any other monitor or have the CRCG9 in PBP mode (Smaller resolution 16:9) while it's booting. Once at the BIOS or OS it can then be plugged into the CRCG9 in regular mode and it will work fine.

**Comment by LattePanda** [comment]
Hi there
We check the spec of the screen. and sorry that we cannot point out the compatibility problem is cause by the Dual QHD or HDMI2.0.
Do you have a type-c hub ? Maybe you can test the DP function in LattePanda type-c port?


Best Regards,

Cain Zhang

LattePanda Team

________________________________

**Comment by Nanoshi** [comment]
On further testing, it looks like if the LP800s is not plugged into a
display through HDMI on boot, then it will disable that interface.

Either not plugged in or not detected at boot disables the interface
preventing the OS using that output.

Please test it on your side. Power off the LP, disconnect the HDMI, power
it on, wait 5 seconds, then connect the HDMI. Does the display work? Is
this a firmware issue? Or specific to my board? I've also already defaulted
the CMOS settings.

**Comment by LattePanda** [comment]
Hi there,
In the first few seconds of booting. the board will initialize and detect peripherals. In the period， any change of peripherals may cause the failure of initialization.
So if you need use HDMI port. We suggest you can plug before powered or after the LattePanda totally boot-up(Waiting for more time). Also please check the RTC battery still have enough power.


Best Regards,

Cain Zhang

LattePanda Team

________________________________
