### ISSUE TITLE
V1 2G32GB Windows 10 drivers don't install or work

### ISSUE THREAD

**Issue by ETHREAL1** [LattePandaTeam/LattePanda-Win10-Software#40]
Hello, First can I ask why your not using official driver packages so that the device manager can just find them?

With that said... The install script does not work and the batch file appears to do nothing...

**Comment by LattePanda** [comment]
here is the driver pack of LattePanda V1.
https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Drivers/4G64GB_Drivers
