### ISSUE TITLE
LattePanda Alpha KR310 m3-8100y boards do not power on with autopoweron bios

### ISSUE THREAD

**Issue by IanButterworth** [LattePandaTeam/LattePanda-Win10-Software#41]
I'm cross-posting this as I'm not sure whether the forum or this issue tracker is more monitored: https://www.lattepanda.com/topic-f6t35524.html

____

I am trying to enable auto-on on a R310 LattePanda Alpha.

With the S70KR300 board, the [R300 instructions are clear](https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/cf36d400edf12f9b9242898d7a93995410b79277/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha%20m3-8100y/Alpha-8100y%20KR300/Alpha%20-8100y%20KR300%20Auto-power-on%20BIOS) with all the necessary files included in the zip.

But for the S70KR310, [the instructions](https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/cf36d400edf12f9b9242898d7a93995410b79277/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha%20m3-8100y) are less clear.

In the [zips provided](https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/cf36d400edf12f9b9242898d7a93995410b79277/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha%20m3-8100y/Alpha-8100y%20KR310) the "EC-Alpha-KR310-Autopoweron.zip" archive only has 3 files:

- FEC64.NSH
- eFuitX64.efi
- S70KR310A-V9-poweron.bin

but the instructions request running:
`fs3:\> AfuEfix64.efi BS-7-S70KR200-K65A-B1A.Bin /p /b /n`
but neither file is available.

If I guess that the first step for the auto poweron bios flash should be
`fs3:> eFuitX64.efi S70KR310A-V9-poweron.bin /p /b /n`
then I get the error "ERROR: unrecognize parameter /p . Aborting."

Further, for the second step in the instructions:
`fs3:\> eFuitX64.efi /u EC-7-S70KR200-K65A-B1A.bin`
it requires a different bin file, where there is only one provided in the zip archive.

Please help me understand which files or instructions should be used to update to the R310 auto poweron bios.

**Comment by Zaherkorechi** [comment]
Hello @IanButterworth,
Did you find the solution for the problem?
Thanks in advance.

**Comment by MrsLardass** [comment]
You just need the three files in the autopoweron folder, in your example

`eFuitX64.efi /u S70KR310A-V9-poweron.bin`

After the flash utility has finished and you have a prompt, type exit to return to bios page, save changes and restart.

The EC-Alpha-KR310-Autopoweron.zip I have just downloaded contains
eFuitX64.efi     
FEC64.NSH     
S70KR310A-auto-poweron.bin
so 
`eFuitX64.efi /u S70KR310A-auto-poweron.bin`
worked for me

**Comment by IanButterworth** [comment]
@MrsLardass `eFuitX64.efi /u S70KR310A-auto-poweron.bin` also "works" for me, but the Alpha doesn't auto power on after this.

Are you saying it does for you?

**Comment by IanButterworth** [comment]
@LattePanda can you help here give clear instructions for updating the R310 to auto power on

**Comment by IanButterworth** [comment]
@LattePanda bump

**Comment by IanButterworth** [comment]
@LattePanda could the RTC battery being low on the alpha affect the boot process here?

**Comment by LattePanda** [comment]
Hi,
do you mean Alpha 8100y KR310? we have update some photos on the tutorial. if you only need Auto-power-on feature, you can start from Step 12 in the tutorial.

**Comment by LattePanda** [comment]
> 

yes, the boot process may be longer if the RTC battery is dead.

**Comment by IanButterworth** [comment]
I am assuming you are referring to https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha%20m3-8100y/Alpha-8100y%20KR310


In step 13 you have this screenshot which shows 5 files

![image](https://user-images.githubusercontent.com/1694067/211635282-85ca34aa-742e-4a34-ab63-2d27d2ce850a.png)

The ones used in the final command are
- eFuitX86.efi
- EC-7-S70KR200-K65A-B1A.bin

Which zip are those files in? I cannot find them.

---

In the discussion above, I assumed (and it was confirmed by @MrsLardass) that the second file should be `S70KR310A-auto-poweron.bin`.

Running `eFuitX64.efi /u S70KR310A-auto-poweron.bin` does not make my KR310 boards auto power on.

---

Putting a brand new rtc battery in the board does not help.

---

Also, even though it is before step 12, step 2 is very vague. Please make it more explicit than saying "Copy the right BIOS files".

**Comment by LattePanda** [comment]
hi,

the pictures in the tutorial is for your reference. The exact file name may vary. you can tell us the CPU model and S/N number of your LattePanda, we can send EC file link to you.

**Comment by IanButterworth** [comment]
`X-S70KR310-KF65A-202800566` is the S/N on the board I am currently testing

**Comment by LattePanda** [comment]
if the CPU model is **m3-8100y**, pls use the following Auto-power-on EC file.
https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha%20m3-8100y/Alpha-8100y%20KR310/EC-Alpha-KR310-Autopoweron.zip

**Comment by IanButterworth** [comment]
Using that file with a KR310 m3-8100y does not result in the board auto powering on.

However, with the KR310 i5-8210y units that we have, the following does work
https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha-8210y/EC-%20Auto%20power%20on.zip

So it seems the issue is that specifically KR310 m3-8100y boards do not auto power on with https://github.com/LattePandaTeam/LattePanda-Win10-Software/blob/master/BIOS%20for%20LattePanda%20Alpha%26Delta/Alpha%20m3-8100y/Alpha-8100y%20KR310/EC-Alpha-KR310-Autopoweron.zip?rgh-link-date=2023-01-13T09%3A31%3A31Z

Can anyone confirm/disprove this issue?

**Comment by RobLawlor2** [comment]
This is also an issue for me, has there been any progress on resolving it.

**Comment by RobLawlor2** [comment]
S/N L-S70KR310-KF65B-221801329
Serial number of device. 
@LattePanda I followed all the steps above and have the same issue, has any internal testing of this file taken place since this issue has been brought to your attention ?

**Comment by RobLawlor2** [comment]
Update: so the S70KR310A-V9-poweron.bin seems to work, however the original file does not. The device no boots up when the power is turned on, cheers

**Comment by LattePanda** [comment]
have you solved the issue? we have done tests on the files and if it still can't work, pls contact techsupport@lattepanda.com for RMA.

**Comment by chris-ngo** [comment]
holyyyy @IanButterworth, 2.5 years late to the party, but THANK YOU for articulating the source/s of confusion among the dumpster fire of documentation for this. i've already bricked one Alpha following LP documentation for BIOS flashing, and the RMA process is more trouble than it's worth. out of curiosity, were you ever able to find a solution? i see mention of a  `S70KR310A-V9-poweron.bin` file, but i'm not even seeing that in any of the provided directories. thanks in advance!
