### ISSUE TITLE
After updating the BIOS, the touch screen does not work in Windows 10

### ISSUE THREAD

**Issue by baalwy** [LattePandaTeam/LattePanda-Win10-Software#42]
After updating the BIOS, the touch screen does not work in Windows 10

(Linux compatible) Alpha-8100y KR300 Default BIOS.rar

**Comment by LattePanda** [comment]
pls follow the guide here to install touch driver again.
https://docs.lattepanda.com/content/alpha_edition/drivers_and_software/#touch-panel-drivers
