### ISSUE TITLE
Boot Error 92 - Lattepanda V1

### ISSUE THREAD

**Issue by Armored-22** [LattePandaTeam/LattePanda-Win10-Software#44]
System will not boot, stuck on LP Logo with code 92 in bottom right.
 
Not unless I use the "Reset system with ME disable ModeMEUD000" in BIOS. 
There is a device error with "Intel Trusted Execution Engine Interface" 
"This device cannot start. (Code 10)
STATUS_DEVICE_POWER_FAILURE"

Some other info;
using a basic dell wired keyboard/mouse 
using wifi
using the official RasPi power cable (tried many different cables and power bricks, yes many were 5v3a's)
I've tried the many different tricks like power/reset hold down and even the one where you hold them and remove/add power etc...
I've tried unplugging everything, did this also and let the system sit for an entire 24+ hours without power

**Comment by alphaarea** [comment]
It is recommended that you contact techsupport@lattepanda.com to determine if it is a hardware failure that requires a RMA
