### ISSUE TITLE
Headless booting

### ISSUE THREAD

**Issue by luisrr1590** [LattePandaTeam/LattePanda-Win10-Software#45]
Hi guys,

Why is it that the LattePanda does not support headless booting.....I've been looking all over for a solution to this and all I have come across is to buy a HDMI Terminator which to be honest that's kind of unacceptable.

Isn't this something you guys can fix with a BIOS update?

Or could you give me the explaination of why is this not possible with these boards?

I'm working with a V1 4gb model by the way.

Thanks

**Comment by luisrr1590** [comment]
Hi, sorry for the late response.

Of course, here's the info:

S/N: KBWNP180406300455
S70CR200-CC55F   Z8350

Please let me know if anything else is needed.

**Comment by LattePanda** [comment]
sorry, it seems hard to change from BIOS side. we suggest you add a HDMI dummy to the HDMI port temporarily.
