### ISSUE TITLE
Why is this on github, there's no source for the drivers?

### ISSUE THREAD

**Issue by marshalcraft** [LattePandaTeam/LattePanda-Win10-Software#5]

**Comment by Tsaukpaetra** [comment]
Yeah, kinda weird. I can't download folders individually from GitHub, I have to get the whole thing.... WTF.

**Comment by LattePanda** [comment]
Hi Sir,


Sorry for the inconvenient, thanks for your reminding, we are going to update it soon!

You can also use the check out function to download the folders you need.


Best Regards,
Kelvin Sun
LattePanda Team
________________________________

**Comment by Tsaukpaetra** [comment]
> You can also use the check out function to download the folders you need.

Yes, but only through a git client, this action is impossible to do through the website itself. ;)

**Comment by LattePanda** [comment]
Hi,


Sorry for the inconvenient again, we are planning to separate these items, do you have any suggestion about it?


by the way, which folder do you need? maybe i can send it to you?


Best Regards,
Kelvin Sun
LattePanda Team
________________________________

**Comment by Tsaukpaetra** [comment]
I just got the whole thing, didn't take too long just puzzled a bit why it's in this form. ;)

**Comment by marshalcraft** [comment]
Can I ask why are you even using GitHub, is it supposed to be used as a free server to distribute software or is it's version control for software development. There isn't any source code developed here. I think your site should be used for driver updates, not GitHub. Not trying to be mean, I like latte panda and the fact it uses intel x86 and windows opposed to arm and Linux. But I don't think this should be place for driver downloads. It overly complicates the matter as GitHub is designed primarily for source code.

**Comment by LattePanda** [comment]
Hi,


At the beginning, we want to make it easier for users to access all resources through one website, and Github is one of the rare resource website which can be accessed all over the world, you know, in some country, people can not access some website like google.

But to be honest, we are considering this seriously. do your have any idea? any opinion will be very helpful.


Thanks


Best Regards,
Kelvin Sun
LattePanda Team
________________________________

**Comment by underdoeg** [comment]
I appreciate having the files on github. That way you get versioning, it is easy to download and has a familiar interface

**Comment by Tsaukpaetra** [comment]
sure. If you want to download everything (or figure out a client's facilities to selectively download the portions you need).

**Comment by underdoeg** [comment]
You can just download specific files or am I missing something?

**Comment by Tsaukpaetra** [comment]
> You can just download specific files or am I missing something?

Yeah. Download individual files. Have fun downloading individual files like Graphics. https://github.com/LattePandaTeam/LattePanda-Win10-Software/tree/master/Drivers/LattePanda_4G64GB_Drivers/MRD-64bit-Intel-Driver-Release/Drivers/Graphics

Ha ha. Much entertain. Good frustrate.

**Comment by underdoeg** [comment]
I am not allowed to post links here. But look for downgit or use svn to checkout a specific folder...

**Comment by Tsaukpaetra** [comment]
Yeah. See my comment [above](https://github.com/LattePandaTeam/LattePanda-Win10-Software/issues/5#issuecomment-303631268).

**Comment by marshalcraft** [comment]
Well the purpose of GitHub is source code versioning and control, if you
want to distribute proprietary binaries you should do it from a site your
company pays to host, not GitHub, though I'm sure it is convenient not
being competent to distribute it yourself and avoiding server costs you
scumbag.

On Wednesday, May 24, 2017, Philip Whitfield <notifications@github.com>
wrote:
> I appreciate having the files on github. That way you get versioning, it
is easy to download and has a familiar interface
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/3_oHFntEECG9-BdFhyeHwZbhuboC0X4ExnqcT3EMrcG4LBCIkONYHIEPqBvp_Sqtx9aebh49RwTv1ya30hw
-hTM97tGOWmQ4epxG-JuDRDEN3NfoMfkwmVtdTptcflMruRoaXZO9tUHvMYg6_ouJ5X-NlAwl4g=s0-d-e1-ft#
https://github.com/notifications/beacon/ARBWHCtq-j_9oB6jArt03ezhrn5oIQh-ks5r88XFgaJpZM4LdjJC.gif>

**Comment by LattePanda** [comment]
We will manage to move the resources without source to dropbox step by step...Sorry for the confusion.
