### ISSUE TITLE
Windows 10 Drivers for x64 not installing

### ISSUE THREAD

**Issue by Bigshooter** [LattePandaTeam/LattePanda-Win10-Software#6]
After installing windows 10 pro on the 4/64, I am unable to get all the drivers installed.  I have included the script output below.

C:\Windows\system32>cd C:\LattePanda-Win10-Software-master\LattePanda-Win10-Software-master\Drivers\LattePanda_4G64GB_Drivers\MRD-64bit-Intel-Driver-Release\Scripts

C:\LattePanda-Win10-Software-master\LattePanda-Win10-Software-master\Drivers\LattePanda_4G64GB_Drivers\MRD-64bit-Intel-Driver-Release\Scripts>install_DF_S70CR100.bat
installing all CherryTrail MRD driver
C:\LattePanda-Win10-Software-master\LattePanda-Win10-Software-master\Drivers\LattePanda_4G64GB_Drivers\MRD-64bit-Intel-Driver-Release\Scripts
**************
Install MBI driver
Microsoft PnP Utility

Processing inf :            MBI.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install TXEI driver
Microsoft PnP Utility

Processing inf :            TXEI.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install PMIC driver
Microsoft PnP Utility

Processing inf :            pmic.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install BM driver
Microsoft PnP Utility

Processing inf :            IntelBatteryManagement.inf
Successfully installed the driver on a device on the system.
Driver package added successfully.
Published name :            oem16.inf

Total attempted:              1
Number successfully imported: 1

****************
Install IO driver
Microsoft PnP Utility

Processing inf :            iai2ce.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install GPIO driver
Microsoft PnP Utility

Processing inf :            iagpioe.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install UART driver
Microsoft PnP Utility

Processing inf :            iauarte.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install SPI driver
Microsoft PnP Utility

Processing inf :            iaspie.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install DPTF driver
Microsoft PnP Utility

Processing inf :            dptf_acpi.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

Microsoft PnP Utility

Processing inf :            dptf_cpu.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

Microsoft PnP Utility

Processing inf :            dptf_pch.inf
Successfully installed the driver on a device on the system.
Driver package added successfully.
Published name :            oem21.inf

Total attempted:              1
Number successfully imported: 1

Microsoft PnP Utility

Processing inf :            esif_manager.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install Audio driver
Microsoft PnP Utility

Processing inf :            isstrtc.inf
Successfully installed the driver on a device on the system.
Driver package added successfully.
Published name :            oem23.inf

Total attempted:              1
Number successfully imported: 1

Microsoft PnP Utility

Processing inf :            rtii2sac.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install ISH driver
Microsoft PnP Utility

Processing inf :            HIDEventFilter.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install Touch driver
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find c:\windows\inf\gt9*.bin
        1 file(s) copied.
Scanning for new hardware.
Scanning completed.
Updating drivers for ACPI\GDIX1001 from C:\LattePanda-Win10-Software-master\LattePanda-Win10-Software-master\Drivers\LattePanda_4G64GB_Drivers\MRD-64bit-Intel-Driver-Release\Drivers\touch\package\GoodixTouchDriver.inf.
Drivers installed successfully.
Scanning for new hardware.
Scanning completed.
Install Camera driver
Microsoft PnP Utility

Processing inf :            iaisp64.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

Microsoft PnP Utility

Processing inf :            iacamera64.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

**************
Install WiFi driver
        1 file(s) copied.
Microsoft PnP Utility

Processing inf :            bcmdhd64.inf
Successfully installed the driver on a device on the system.
Driver package added successfully.
Published name :            oem30.inf

Total attempted:              1
Number successfully imported: 1

Microsoft PnP Utility

Processing inf :            bcmfn2.inf
Successfully installed the driver on a device on the system.
Driver package added successfully.
Published name :            oem31.inf

Total attempted:              1
Number successfully imported: 1

**************
Install Bluetooth driver
'install' is not recognized as an internal or external command,
operable program or batch file.
**************
Install Sensor driver
**************
Install GPS driver
**************
Install graphic driver ....
ECHO is off.
Microsoft PnP Utility

Processing inf :            igdlh64.inf
Failed to install the driver on any of the devices on the system : No more data is available.

Total attempted:              1
Number successfully imported: 0

All Intel drivers for CherryTrail MRD are installed !

**Comment by LattePanda** [comment]
Dear friend,

We've updated all packages to make it easier for everyone to install and download the driver pack and bios zip files. Please check the latest update. Thanks. 

Best

**Comment by LattePanda** [comment]
BTW, here's video tutorial contributed by user, which explains how to install driver pack on Windows x64 system. 
http://www.lattepanda.com/forum/viewtopic.php?f=10&t=1042
Hope it's helpful!

Best

**Comment by Schnoffel** [comment]
Having the same issues on current Windows 10 like this error: "'install' is not recognized as an internal or external command [...]"

The install script does not properly work. I also had a Bluescreen while using the Script. When I go to device manager and click an "Look for new hardware" (in German "Nach geänderter Hardware suchen") the whole system restarts with no message.
