### ISSUE TITLE
Ghost backup problem on LattePanda

### ISSUE THREAD

**Issue by Batyrbek** [LattePandaTeam/LattePanda-Win10-Software#7]
Recently I have discovered that Ghost.exe copied USB boot (FAT32, free dos using rufus tool) cannot start ghost on LattePanda(2G/32Gb). 
What other system backup (ghosting) method available?

**Comment by LattePanda** [comment]
Dear friend,

There's a user posted a detail tutorial to share the best to clone a backup for your system:
http://www.lattepanda.com/forum/viewtopic.php?f=6&t=1210&p=5283&hilit=system+backup#p5283

Hope it's help! Sorry for the long term delay.

Best
