### ISSUE TITLE
BIOS 1.0 Roll Back

### ISSUE THREAD

**Issue by mxrclxst** [LattePandaTeam/LattePanda-Win10-Software#9]
Hello,

I'm getting an error trying to roll back to the default BIOS 1.0. I have the 4GB 64bit Z8300 LattePanda

```
Reading flash . . . . . . . . . . . . . . . done
- ME Data Size checking  .  ok
Secure Flash enabled, recalculate ROM size with signature . . . Enable.
- FFS checksums . . . . . . . . . ok
bb- Error: Rom image layout detected Rom Hole is redesigned.
```

Please advise.

Thanks

**Comment by mxrclxst** [comment]
I found the solution.

Edit the startup.nsh file and add `/l`  at the end of of the commands

**Comment by abbiebinbin** [comment]
I have same problem. Already edited startup.nsh with add "/l" but no working. I need to roll back to default BIOS. :( Need some help..

**Comment by LattePanda** [comment]
@abbiebinbin  Did you flash any other bios version on this board？ And did you confirm the version of lattepanda board？

**Comment by abbiebinbin** [comment]
I wrong flash v1.1 bios to my cr110 z8300 LP. But i check my bios detail it list cr100 model. I still can boot to window. Only the problem is after clean install the bluetooth and wifi not working. I try install driver but keep said error code 10. I cant reflash back to default bios.

**Comment by mxrclxst** [comment]
Bluetooth and wifi is a driver issue due to Win 10  creators update.
Rolling back drivers to an older version fixes it or installing the
manufacturer driver instead of the drivers windows finds automatically.

**Comment by abbiebinbin** [comment]
Hi, is after clean install window 10. Haven't update to win 10 creators. Normally after re-install the bluetooth is auto active right? I remember first time re-install it have bluetooth. After I flash my bios then the bluetooth no working anymore.

**Comment by LattePanda** [comment]
@abbiebinbin check the Device Manager -> System devices -> Realtek Bluetooth UART Bus Driver， is this driver installed correctly？ We leave the WiFi and Bluetooth driver v1.0 on the LattePanda win10 software  driver repository

**Comment by abbiebinbin** [comment]
Don't have this driver installed in my LP, I got download driver zip files from github. But it show broadcom not realtek. Is it in BT folder for bluetooth driver? Mine is 4/64gb ver.

**Comment by abbiebinbin** [comment]
broadcom serial bus driver over uart bus enumerator is this one? but code 10.
